name: FGR
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - numpy=2.2.3
  - pandas=2.2.3
  - scikit-learn=1.6.1
  - omegaconf=2.3.0
  - tqdm
  - pytest
  - isort
  - black
  - pip
  - pip:
    - torch==2.6.0
    - torchvision==0.21.0
    - transformers==4.49.0
    - torchmetrics-1.6.3
    - fvcore==0.1.5.post20221221
